Repository auth0/auth0-spring-security-api, pull requests merged in 2022-01, with the labels that each got.

#60 Update README guidance
  README.md
Labels: review:tiny

#62 Update java jwt and jwks
  lib/build.gradle
Labels: CH: Security, review:tiny

#64 Update gradle and publishing plugin
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: CH: Changed, review:tiny

#65 Release 1.4.2
  CHANGELOG.md
  README.md
Labels: review:tiny
