Repository auth0/auth0-spring-security-api, pull requests merged in 2022-03, with the labels that each got.

#66 Update auth0 dependencies to address CVE-2020-36518
  lib/build.gradle
Labels: CH: Changed, CH: Security, review:small

#67 Release 1.5.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#68 Bump transitive jackson dependencies in auth0 libraries
  lib/build.gradle
Labels: CH: Security, dependencies, review:tiny
